### ISSUE TITLE
API give error

### ISSUE THREAD

**Issue by calvinti12** [majhcc/from-tiktok-to-instagram-reposter#1]
API given error When fetching new videos

**Comment by m7medVision** [comment]
This is the source code of Api if you wanna fix it.

https://github.com/majhcc/M-API/blob/1259db74629106e94dc9c616bb0f26def81e3171/src/tiktok/tiktok_tools.py#L23

**Comment by m7medVision** [comment]
i just updated the repo, I think it now work
